name = "BloodStorageInSilico"
uuid = "12fa0bc3-1996-4702-b249-fafc788310f3"
version = "0.1.0"
authors = ["Alicia M. Key <alicia.m.key@cuanschutz.edu"]

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[compat]
AlgebraOfGraphics = "0.11.8"
CSV = "0.10.15"
CairoMakie = "0.15.6"
CategoricalArrays = "1.0.1"
Clustering = "0.15.8"
Combinatorics = "1.0.3"
DataFrames = "1.8.0"
DataFramesMeta = "0.15.4"
Distributions = "0.25.122"
GLMakie = "0.13.6"
HypothesisTests = "0.11.5"
JuliaFormatter = "2.1.6"
KernelDensity = "0.6.10"
Makie = "0.24.6"
MultipleTesting = "0.6.0"
Statistics = "1.11.1"
StatsBase = "0.34.6"
StatsModels = "0.7.7"
ThreadsX = "0.1.12"
